'use client';

import { useState } from 'react';
import { Download } from 'lucide-react';
import { Citation } from '@/lib/types';

interface ExportButtonProps {
  report: string;
  topic: string;
  citations: Citation[];
  sessionId: string;
}

export function ExportButton({ report, topic, citations }: ExportButtonProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [exporting, setExporting] = useState(false);

  const exportMarkdown = () => {
    setExporting(true);
    const date = new Date().toISOString().split('T')[0];
    const citationsSection =
      citations.length > 0
        ? '\n\n## Sources\n' +
          citations.map((c, i) => `${i + 1}. [${c.title}](${c.url})`).join('\n')
        : '';

    const content = `# ${topic}\n\n*Exported from Mnemox on ${date}*\n\n${report}${citationsSection}`;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${topic.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${date}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setExporting(false);
    setIsOpen(false);
  };

  const exportPDF = async () => {
    setExporting(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      const maxWidth = pageWidth - margin * 2;
      let y = 20;

      // Title
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(20, 20, 20);
      doc.text(topic, margin, y);
      y += 10;

      // Date line
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 100, 100);
      doc.text(`Generated by Mnemox · ${new Date().toLocaleDateString()}`, margin, y);
      y += 10;

      // Divider
      doc.setDrawColor(200, 200, 200);
      doc.line(margin, y, pageWidth - margin, y);
      y += 8;

      // Report content — strip common markdown symbols
      const cleanText = report
        .replace(/#{1,6}\s/g, '')
        .replace(/\*\*/g, '')
        .replace(/\*/g, '')
        .replace(/`/g, '')
        .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1');

      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(30, 30, 30);

      const lines = doc.splitTextToSize(cleanText, maxWidth);
      for (const line of lines) {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        doc.text(line, margin, y);
        y += 6;
      }

      // Citations section
      if (citations.length > 0) {
        if (y > 250) {
          doc.addPage();
          y = 20;
        }
        y += 6;
        doc.setFontSize(13);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(20, 20, 20);
        doc.text('Sources', margin, y);
        y += 8;

        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(60, 60, 60);
        citations.forEach((c, i) => {
          if (y > 270) {
            doc.addPage();
            y = 20;
          }
          const citText = `${i + 1}. ${c.title} — ${c.url}`;
          const citLines = doc.splitTextToSize(citText, maxWidth);
          doc.text(citLines, margin, y);
          y += citLines.length * 5 + 2;
        });
      }

      const filename = `${topic.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.pdf`;
      doc.save(filename);
    } catch (err) {
      console.error('PDF export failed:', err);
    }
    setExporting(false);
    setIsOpen(false);
  };

  return (
    <div className="relative">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center gap-2 text-sm text-gray-400 hover:text-white border border-gray-800 hover:border-gray-600 px-3 py-1.5 rounded-lg transition-colors"
        aria-label="Export report"
      >
        <Download size={14} />
        {exporting ? 'Exporting…' : 'Export'}
      </button>

      {isOpen && !exporting && (
        <>
          {/* backdrop */}
          <div className="fixed inset-0 z-40" onClick={() => setIsOpen(false)} />
          <div className="absolute right-0 top-full mt-1 bg-[#111] border border-gray-800 rounded-lg overflow-hidden z-50 min-w-[140px] shadow-xl">
            <button
              onClick={exportMarkdown}
              className="w-full text-left px-4 py-2.5 text-sm text-gray-300 hover:bg-gray-800 hover:text-white transition-colors flex items-center gap-2"
            >
              <span>📄</span> Markdown
            </button>
            <button
              onClick={exportPDF}
              className="w-full text-left px-4 py-2.5 text-sm text-gray-300 hover:bg-gray-800 hover:text-white transition-colors flex items-center gap-2 border-t border-gray-800"
            >
              <span>📋</span> PDF
            </button>
          </div>
        </>
      )}
    </div>
  );
}
