# state.py
# Defines the shared AgentState TypedDict used across all LangGraph nodes.
# Every field is passed between nodes as the graph executes.

from typing import TypedDict, Annotated
import operator


class AgentState(TypedDict):
    # The research topic provided by the user
    topic: str

    # Search queries generated by the LLM for this topic
    search_queries: list[str]

    # Raw results returned by Tavily search API
    search_results: list[dict]

    # Cleaned text extracted from each scraped URL
    # Each dict: { title, url, content, word_count }
    scraped_content: list[dict]

    # Key insights extracted by the LLM from scraped content
    # Each dict: { insight, source_url, source_title, confidence }
    extracted_insights: list[dict]

    # Named entities extracted from the content
    # Each dict: { name, type, description }
    entities: list[dict]

    # Relationships between entities
    # Each dict: { source, relation, target }
    relationships: list[dict]

    # Relevant context string retrieved from past sessions (vector + graph)
    memory_context: str

    # Final markdown report generated by the LLM
    report: str

    # Structured citation list
    # Each dict: { title, url, accessed_date }
    citations: list[dict]

    # Unique identifier for this research session
    session_id: str

    # LangGraph message history for conversational context
    messages: list

    # Unique identifier of the authenticated user
    user_id: str

